name: ✅ CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      # Remove before merging with main
      - exceptions
  schedule:
    - cron: "0 12 * * 0"

jobs:
  ci:
    uses: libhal/ci/.github/workflows/library_check.yml@5.x.y
    secrets: inherit

  test-cortex-m4f:
    uses: libhal/ci/.github/workflows/deploy.yml@5.x.y
    with:
      version: exceptions
      arch: cortex-m4f
      os: baremetal
      compiler: gcc
      compiler_version: 12.3
      compiler_package: arm-gnu-toolchain
    secrets: inherit

  test-demos:
    uses: libhal/ci/.github/workflows/demo_builder.yml@5.x.y
    with:
      version: exceptions
      compiler_profile_url: https://github.com/libhal/arm-gnu-toolchain.git
      compiler_profile: v1/arm-gcc-12.3
      compiler_profile_branch: main
      platform_profile_url: https://github.com/libhal/libhal-lpc40.git
      platform_profile: v2/lpc4078
      platform_profile_branch: exception
    secrets: inherit
