name: ✅ CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      # Remove before merging with main
      - exceptions
  schedule:
    - cron: "0 12 * * 0"

jobs:
  ci:
    uses: libhal/ci/.github/workflows/library_check.yml@5.x.y
    secrets: inherit

  test-cortex-m4f:
    uses: libhal/ci/.github/workflows/deploy.yml@5.x.y
    with:
      arch: cortex-m4f
      os: baremetal
      compiler_package: arm-gnu-toolchain
    secrets: inherit

  test-demos:
    uses: libhal/ci/.github/workflows/demo_builder.yml@5.x.y
    with:
      platform_profile: conan/profiles/v2/
      profile: lpc4078
    secrets: inherit
