name: ✅ libhal Checks

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0'

jobs:
  lint:
    uses: libhal/libhal/.github/workflows/lint.yml@main
    with:
      library: liblpc40xx
  docs:
    uses: libhal/libhal/.github/workflows/docs.yml@main
    with:
      library: liblpc40xx
  # tests:
  #   uses: libhal/libhal/.github/workflows/tests.yml@main
  #   with:
  #     library: liblpc40xx
