on:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 0'

jobs:
  lint:
    uses: SJSU-Dev2/libembeddedhal/.github/workflows/lint.yml@main
    with:
      library: libarmcortex
  docs:
    uses: SJSU-Dev2/libembeddedhal/.github/workflows/docs.yml@main
    with:
      library: libarmcortex
  # tests:
  #   uses: SJSU-Dev2/libembeddedhal/.github/workflows/tests.yml@main
  #   with:
  #     library: libarmcortex
